// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type NotificationMail struct {
	ID           int32
	Recipient    string
	TemplateName string
	Status       string
	Details      sql.NullString
	Data         json.RawMessage
	AttemptedAt  time.Time
}
