// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notifications.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createNotificationLog = `-- name: CreateNotificationLog :exec
INSERT INTO notification_logs (
    recipient,
    template_name,
    status,
    details,
    data,
    attempted_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateNotificationLogParams struct {
	Recipient    string
	TemplateName string
	Status       string
	Details      sql.NullString
	Data         json.RawMessage
	AttemptedAt  time.Time
}

func (q *Queries) CreateNotificationLog(ctx context.Context, arg CreateNotificationLogParams) error {
	_, err := q.db.ExecContext(ctx, createNotificationLog,
		arg.Recipient,
		arg.TemplateName,
		arg.Status,
		arg.Details,
		arg.Data,
		arg.AttemptedAt,
	)
	return err
}
